<script>
    import LastRuns from "./LastRuns.svelte";
    import {TestTube, Scan} from "phosphor-svelte";
</script>

<div class="h-full row gap-3">
    <div class="column">
        <div class="card h-full">
            <div class="card-header">
                <h1>Overview</h1>
            </div>
            <div class="card-body">
                <p>
                    To start the program, create a new pipeline first.
                </p>

                <p>
                    You can either use test data or scanner data.
                </p>

                <p>
                    Test data is generated by the program and can be used to test the program.
                    You can customize the test data using the .blend file in the testdata/scan folder.
                </p>
            </div>
            <div class="card-footer d-flex justify-content-between">
                <a href="/pipelines/new?source=test" class="btn btn-primary">
                    <TestTube size="20"/> &nbsp; Use Test Data</a>
                <a
                        href="/#pipelines/new?source=scan"
                        class="btn btn-primary"
                        on:click|preventDefault={() => {
                            console.log("The scanner is not available yet.");
                        }}
                >
                    <Scan size="20"/> &nbsp; Use Scanner Data</a>
            </div>
        </div>
    </div>
    <div class="column">
        <div class="card">
            <div class="card-header">
                <h1>Last Runs</h1>
            </div>
            <div class="card-body overflow-hidden h-full">
                <LastRuns/>
            </div>
        </div>
    </div>
</div>